service: "serverless-graphql-blog"

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-west-2
  memory: 1024
  timeout: 6
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["PostsDynamo", "Arn"] }
        - { "Fn::GetAtt": ["AuthorsDynamo", "Arn"] }
        - { "Fn::GetAtt": ["CommentsDynamo", "Arn"] }

functions:
  sadiavas:
    handler: "index.graphql"
    include:
      - blog/
      - index.js
    events: 
      - http:
          path: "blog/graphql"
          method: "POST"

    custom: 
      excludePatterns: []
      optimize: 
        exclude: 
          - "aws-sdk"
        transforms: 
          - 
            name: "babelify"
            opts: 
              presets: 
                - "es2015"

resources:
  Resources: 
    PostsDynamo: 
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: "Retain"
      Properties: 
        AttributeDefinitions: 
          - 
            AttributeName: "id"
            AttributeType: "S"
        KeySchema: 
          - 
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "${self:service}-posts-${self:provider.stage}"
    AuthorsDynamo: 
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: "Retain"
      Properties: 
        AttributeDefinitions: 
          - 
            AttributeName: "id"
            AttributeType: "S"
        KeySchema: 
          - 
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "${self:service}-authors-${self:provider.stage}"
    CommentsDynamo: 
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: "Retain"
      Properties: 
        AttributeDefinitions: 
          - 
            AttributeName: "id"
            AttributeType: "S"
        KeySchema: 
          - 
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: "${self:service}-comments-${self:provider.stage}"

